import { ClassifiedChange, Severity } from './rules';
import { DiffResult } from './diff';
import { ClassifiedGraphQLChange, Severity as GQLSeverity } from './parsers/graphql-rules';
import { GraphQLDiffResult } from './parsers/graphql-diff';
import { ClassifiedGrpcChange, GrpcSeverity } from './parsers/grpc-rules';
import { GrpcDiffResult } from './parsers/grpc-diff';

export interface ReportOptions {
  includeSafeChanges?: boolean;
  /** If true, exit code will be non-zero when breaking changes exist (CI mode) */
  strict?: boolean;
}

export interface Report {
  markdown: string;
  hasBreakingChanges: boolean;
  hasWarnings: boolean;
  summary: string;
}

function severityIcon(severity: Severity | GQLSeverity | GrpcSeverity): string {
  switch (severity) {
    case 'breaking':
    case GQLSeverity.BREAKING:
    case GrpcSeverity.BREAKING: return '🔴';
    case 'warning':
    case GQLSeverity.WARNING:
    case GrpcSeverity.WARNING: return '🟡';
    case 'safe':
    case GQLSeverity.SAFE:
    case GrpcSeverity.SAFE: return '🟢';
    default: return '⚪';
  }
}

function severityHeader(severity: Severity | GQLSeverity | GrpcSeverity): string {
  switch (severity) {
    case 'breaking':
    case GQLSeverity.BREAKING:
    case GrpcSeverity.BREAKING: return 'BREAKING CHANGES';
    case 'warning':
    case GQLSeverity.WARNING:
    case GrpcSeverity.WARNING: return 'WARNINGS';
    case 'safe':
    case GQLSeverity.SAFE:
    case GrpcSeverity.SAFE: return 'SAFE CHANGES';
    default: return 'UNKNOWN';
  }
}

function renderSection(severity: Severity | GQLSeverity | GrpcSeverity, changes: ClassifiedGraphQLChange[] | ClassifiedChange[] | ClassifiedGrpcChange[]): string {
  if (changes.length === 0) return '';
  let section = `## ${severityIcon(severity)} ${severityHeader(severity)}\n\n`;
  section += changes.map(c => `- ${(c as { message: string }).message}`).join('\n');
  section += '\n\n';
  return section;
}

// ---------- OpenAPI Report ----------

export function generateMarkdownReport(
  diff: DiffResult,
  classified: ClassifiedChange[],
  options: ReportOptions = {}
): string {
  const { includeSafeChanges = true, strict = false } = options;
  const visible = includeSafeChanges
    ? classified
    : classified.filter(c => c.severity !== 'safe');

  const breaking = visible.filter(c => c.severity === 'breaking');
  const warnings = visible.filter(c => c.severity === 'warning');
  const safe = visible.filter(c => c.severity === 'safe');

  let md = `# Contract Guard Report\n\n`;
  md += `**Old version:** \`${diff.oldSpec.title}\` ${diff.oldSpec.version}\n`;
  md += `**New version:** \`${diff.newSpec.title}\` ${diff.newSpec.version}\n\n`;

  md += renderSection('breaking', breaking);
  md += renderSection('warning', warnings);
  if (includeSafeChanges) {
    md += renderSection('safe', safe);
  }

  md += '---\n\n';
  if (strict && breaking.length > 0) {
    md += `> ⚠ **Strict mode**: ${breaking.length} breaking change(s) detected. Failing CI.\n`;
  } else {
    md += `> Generated by \`contract-guard\` V2 (OpenAPI).\n`;
  }

  return md.trimEnd() + '\n';
}

export function buildReport(
  diff: DiffResult,
  classified: ClassifiedChange[],
  options: ReportOptions = {}
): Report {
  const hasBreakingChanges = classified.some(c => c.severity === 'breaking');
  const hasWarnings = classified.some(c => c.severity === 'warning');

  const breakingCount = classified.filter(c => c.severity === 'breaking').length;
  const warningCount = classified.filter(c => c.severity === 'warning').length;
  const safeCount = classified.filter(c => c.severity === 'safe').length;

  const summary = `${breakingCount} breaking, ${warningCount} warning(s), ${safeCount} safe`;

  return {
    markdown: generateMarkdownReport(diff, classified, options),
    hasBreakingChanges,
    hasWarnings,
    summary
  };
}

// ---------- GraphQL Report ----------

export function generateGraphQLReport(
  diff: GraphQLDiffResult,
  classified: ClassifiedGraphQLChange[],
  options: ReportOptions = {}
): string {
  const { includeSafeChanges = true, strict = false } = options;
  const visible = includeSafeChanges
    ? classified
    : classified.filter(c => c.severity !== GQLSeverity.SAFE);

  const breaking = visible.filter(c => c.severity === GQLSeverity.BREAKING);
  const warnings = visible.filter(c => c.severity === GQLSeverity.WARNING);
  const safe = visible.filter(c => c.severity === GQLSeverity.SAFE);

  const typeCount = diff.newSchema.types.size;

  let md = `# Contract Guard Report (GraphQL)\n\n`;
  md += `**Schema:** \`${diff.oldSchema.title}\`\n`;
  md += `**Types:** ${typeCount}\n\n`;

  md += renderSection(GQLSeverity.BREAKING, breaking);
  md += renderSection(GQLSeverity.WARNING, warnings);
  if (includeSafeChanges) {
    md += renderSection(GQLSeverity.SAFE, safe);
  }

  md += '---\n\n';
  if (strict && breaking.length > 0) {
    md += `> ⚠ **Strict mode**: ${breaking.length} breaking change(s) detected. Failing CI.\n`;
  } else {
    md += `> Generated by \`contract-guard\` V2 (GraphQL).\n`;
  }

  return md.trimEnd() + '\n';
}

export function buildGraphQLReport(
  diff: GraphQLDiffResult,
  classified: ClassifiedGraphQLChange[],
  options: ReportOptions = {}
): Report {
  const hasBreakingChanges = classified.some(c => c.severity === GQLSeverity.BREAKING);
  const hasWarnings = classified.some(c => c.severity === GQLSeverity.WARNING);

  const breakingCount = classified.filter(c => c.severity === GQLSeverity.BREAKING).length;
  const warningCount = classified.filter(c => c.severity === GQLSeverity.WARNING).length;
  const safeCount = classified.filter(c => c.severity === GQLSeverity.SAFE).length;

  const summary = `${breakingCount} breaking, ${warningCount} warning(s), ${safeCount} safe`;

  return {
    markdown: generateGraphQLReport(diff, classified, options),
    hasBreakingChanges,
    hasWarnings,
    summary
  };
}

// ---------- gRPC Report ----------

export function generateGrpcReport(
  diff: GrpcDiffResult,
  classified: ClassifiedGrpcChange[],
  options: ReportOptions = {}
): string {
  const { includeSafeChanges = true, strict = false } = options;
  const visible = includeSafeChanges
    ? classified
    : classified.filter(c => c.severity !== GrpcSeverity.SAFE);

  const breaking = visible.filter(c => c.severity === GrpcSeverity.BREAKING);
  const warnings = visible.filter(c => c.severity === GrpcSeverity.WARNING);
  const safe = visible.filter(c => c.severity === GrpcSeverity.SAFE);

  const messageCount = diff.newProto.messages.size;
  const serviceCount = diff.newProto.services.size;

  let md = `# Contract Guard Report (gRPC)\n\n`;
  md += `**Package:** \`${diff.newProto.package || '(no package)'}\`\n`;
  md += `**Messages:** ${messageCount}  **Services:** ${serviceCount}\n\n`;

  md += renderSection(GrpcSeverity.BREAKING, breaking);
  md += renderSection(GrpcSeverity.WARNING, warnings);
  if (includeSafeChanges) {
    md += renderSection(GrpcSeverity.SAFE, safe);
  }

  md += '---\n\n';
  if (strict && breaking.length > 0) {
    md += `> ⚠ **Strict mode**: ${breaking.length} breaking change(s) detected. Failing CI.\n`;
  } else {
    md += `> Generated by \`contract-guard\` V2 (gRPC).\n`;
  }

  return md.trimEnd() + '\n';
}

export function buildGrpcReport(
  diff: GrpcDiffResult,
  classified: ClassifiedGrpcChange[],
  options: ReportOptions = {}
): Report {
  const hasBreakingChanges = classified.some(c => c.severity === GrpcSeverity.BREAKING);
  const hasWarnings = classified.some(c => c.severity === GrpcSeverity.WARNING);

  const breakingCount = classified.filter(c => c.severity === GrpcSeverity.BREAKING).length;
  const warningCount = classified.filter(c => c.severity === GrpcSeverity.WARNING).length;
  const safeCount = classified.filter(c => c.severity === GrpcSeverity.SAFE).length;

  const summary = `${breakingCount} breaking, ${warningCount} warning(s), ${safeCount} safe`;

  return {
    markdown: generateGrpcReport(diff, classified, options),
    hasBreakingChanges,
    hasWarnings,
    summary
  };
}