import { ClassifiedChange, Severity } from './rules';
import { DiffResult } from './diff';
import { ClassifiedGraphQLChange, Severity as GQLSeverity } from './parsers/graphql-rules';
import { GraphQLDiffResult } from './parsers/graphql-diff';

export interface ReportOptions {
  includeSafeChanges?: boolean;
  /** If true, exit code will be non-zero when breaking changes exist (CI mode) */
  strict?: boolean;
}

export interface Report {
  markdown: string;
  hasBreakingChanges: boolean;
  hasWarnings: boolean;
  summary: string;
}

function severityIcon(severity: Severity | GQLSeverity): string {
  switch (severity) {
    case Severity.BREAKING: return '🔴';
    case Severity.WARNING: return '🟡';
    case Severity.SAFE: return '🟢';
  }
}

function severityHeader(severity: Severity | GQLSeverity): string {
  switch (severity) {
    case Severity.BREAKING: return 'BREAKING CHANGES';
    case Severity.WARNING: return 'WARNINGS';
    case Severity.SAFE: return 'SAFE CHANGES';
  }
}

function renderSection(severity: Severity | GQLSeverity, changes: Array<{ message: string }>): string {
  if (changes.length === 0) return '';
  let section = `## ${severityIcon(severity)} ${severityHeader(severity)}\n\n`;
  section += changes.map(c => `- ${c.message}`).join('\n');
  section += '\n\n';
  return section;
}

// ---------- OpenAPI Report ----------

export function generateMarkdownReport(
  diff: DiffResult,
  classified: ClassifiedChange[],
  options: ReportOptions = {}
): string {
  const { includeSafeChanges = true, strict = false } = options;
  const visible = includeSafeChanges
    ? classified
    : classified.filter(c => c.severity !== Severity.SAFE);

  const breaking = visible.filter(c => c.severity === Severity.BREAKING);
  const warnings = visible.filter(c => c.severity === Severity.WARNING);
  const safe = visible.filter(c => c.severity === Severity.SAFE);

  let md = `# Contract Guard Report\n\n`;
  md += `**Old version:** \`${diff.oldSpec.title}\` ${diff.oldSpec.version}\n`;
  md += `**New version:** \`${diff.newSpec.title}\` ${diff.newSpec.version}\n\n`;

  md += renderSection(Severity.BREAKING, breaking);
  md += renderSection(Severity.WARNING, warnings);
  if (includeSafeChanges) {
    md += renderSection(Severity.SAFE, safe);
  }

  md += '---\n\n';
  if (strict && breaking.length > 0) {
    md += `> ⚠ **Strict mode**: ${breaking.length} breaking change(s) detected. Failing CI.\n`;
  } else {
    md += `> Generated by \`contract-guard\` V2 (OpenAPI).\n`;
  }

  return md.trimEnd() + '\n';
}

export function buildReport(
  diff: DiffResult,
  classified: ClassifiedChange[],
  options: ReportOptions = {}
): Report {
  const hasBreakingChanges = classified.some(c => c.severity === Severity.BREAKING);
  const hasWarnings = classified.some(c => c.severity === Severity.WARNING);

  const breakingCount = classified.filter(c => c.severity === Severity.BREAKING).length;
  const warningCount = classified.filter(c => c.severity === Severity.WARNING).length;
  const safeCount = classified.filter(c => c.severity === Severity.SAFE).length;

  const summary = `${breakingCount} breaking, ${warningCount} warning(s), ${safeCount} safe`;

  return {
    markdown: generateMarkdownReport(diff, classified, options),
    hasBreakingChanges,
    hasWarnings,
    summary
  };
}

// ---------- GraphQL Report ----------

export function generateGraphQLReport(
  diff: GraphQLDiffResult,
  classified: ClassifiedGraphQLChange[],
  options: ReportOptions = {}
): string {
  const { includeSafeChanges = true, strict = false } = options;
  const visible = includeSafeChanges
    ? classified
    : classified.filter(c => c.severity !== GQLSeverity.SAFE);

  const breaking = visible.filter(c => c.severity === GQLSeverity.BREAKING);
  const warnings = visible.filter(c => c.severity === GQLSeverity.WARNING);
  const safe = visible.filter(c => c.severity === GQLSeverity.SAFE);

  const typeCount = diff.newSchema.types.size;

  let md = `# Contract Guard Report (GraphQL)\n\n`;
  md += `**Schema:** \`${diff.oldSchema.title}\`\n`;
  md += `**Types:** ${typeCount}\n\n`;

  md += renderSection(GQLSeverity.BREAKING, breaking);
  md += renderSection(GQLSeverity.WARNING, warnings);
  if (includeSafeChanges) {
    md += renderSection(GQLSeverity.SAFE, safe);
  }

  md += '---\n\n';
  if (strict && breaking.length > 0) {
    md += `> ⚠ **Strict mode**: ${breaking.length} breaking change(s) detected. Failing CI.\n`;
  } else {
    md += `> Generated by \`contract-guard\` V2 (GraphQL).\n`;
  }

  return md.trimEnd() + '\n';
}

export function buildGraphQLReport(
  diff: GraphQLDiffResult,
  classified: ClassifiedGraphQLChange[],
  options: ReportOptions = {}
): Report {
  const hasBreakingChanges = classified.some(c => c.severity === GQLSeverity.BREAKING);
  const hasWarnings = classified.some(c => c.severity === GQLSeverity.WARNING);

  const breakingCount = classified.filter(c => c.severity === GQLSeverity.BREAKING).length;
  const warningCount = classified.filter(c => c.severity === GQLSeverity.WARNING).length;
  const safeCount = classified.filter(c => c.severity === GQLSeverity.SAFE).length;

  const summary = `${breakingCount} breaking, ${warningCount} warning(s), ${safeCount} safe`;

  return {
    markdown: generateGraphQLReport(diff, classified, options),
    hasBreakingChanges,
    hasWarnings,
    summary
  };
}